name: "build"

on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.7.0
        with:
          distribution: 'adopt'
          java-version: '14'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run
        run: |
          cd intentional
          cp resources/explain/students.csv resources/intention
          chmod +x *.sh
          bash init.sh
          bash build.sh
          bash download.sh
          bash start.sh
          bash stop.sh
      - name: Run the notebooks
        run: |
          cd intentional
          bash init.sh
          cd src/main/python
          bash runNotebooks.sh

  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: package.json
      - uses: actions/setup-java@v4.7.0
        with:
          distribution: 'adopt'
          java-version: '14'
      - name: Deploy
        run: |
          cd intentional
          ./gradlew shadowJar
          cd ..
          mkdir -p dist/
          cp intentional/build/libs/* dist/
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
